Hospital_Management_Systems/Hospital_Management_System/Controllers/PatientsController.cs
using Hospital_Management_System.Models;
using Hospital_Management_System.Repositories;
using Hospital_Management_System.Repositories.Interfaces;
using Hospital_Management_System.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using X.PagedList;


namespace Hospital_Management_System.Controllers
{
    [Authorize]
    public class PatientsController : Controller
    {
        private readonly PatientDbContext db = new PatientDbContext();
        IGenericRepo<Patient> repo;
        public PatientsController()
        {
            this.repo = new GenericRepo<Patient>(db);
        }
        //GET: Patients
        [AllowAnonymous]
        public ActionResult Index(int pg = 1)
        {
            var data = this.repo.GetAll("Appointments").ToPagedList(pg, 5);
            return View(data);
        }
        public ActionResult Create()
        {

            PatientInputModel db = new PatientInputModel();
            db.Appointments.Add(new Appointment { });
            return View(db);
        }
        [HttpPost]
        public ActionResult Create(PatientInputModel data, string act = "")
        {
            if (act == "add")
            {
                data.Appointments.Add(new Appointment { });

                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                data.Appointments.RemoveAt(index);
                foreach (var item in ModelState.Values)
                {
                    item.Errors.Clear();
                }
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    var b = new Patient
                    {
                        PatientName = data.PatientName,
                        AdmissionDate = data.AdmissionDate,
                        Mobile = data.Mobile,
                        Gender = data.Gender,
                    };
                    string ext = Path.GetExtension(data.Picture.FileName);
                    string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Server.MapPath("~/Pictures/") + fileName;
                    data.Picture.SaveAs(savePath);
                    b.Picture = fileName;
                    foreach (var l in data.Appointments)
                    {

                        b.Appointments.Add(l);
                    }
                    this.repo.Insert(b);

                }
            }
            ViewBag.Act = act;
            return PartialView("_CreatePartial", data);
        }
        public ActionResult Edit(int id)
        {
            var x = this.repo.Get(id, "Appointments");
            var c = new PatientEditModel
            {
                Id = x.Id, 
                PatientName = x.PatientName,
                AdmissionDate = x.AdmissionDate,
                Mobile = x.Mobile,
                Gender = x.Gender,
                Appointments = x.Appointments.ToList()
            };


            ViewBag.CurrentPic = x.Picture;

            return View(c);
        }

        [HttpPost]
        public ActionResult Edit(PatientEditModel data, string act = "")
        {
            if (act == "add")
            {
                data.Appointments.Add(new Appointment { AppointmentDate=DateTime.Today });
                foreach (var t in ModelState.Values)
                {

                    t.Errors.Clear();
                }
            }

            if (act.StartsWith("remove"))
            {

                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));

                data.Appointments.RemoveAt(index);
                foreach (var t in ModelState.Values)
                {

                    t.Errors.Clear();
                }
            }

            if (act == "update")
            {

                if (ModelState.IsValid)
                {
                     
                    var a = db.Patients.First(x => x.Id == data.Id);

                    a.PatientName = data.PatientName;
                    a.AdmissionDate = data.AdmissionDate;
                    a.Mobile = data.Mobile;
                    a.Gender = data.Gender;
                    if (data.Picture != null)
                    {

                        string ext = Path.GetExtension(data.Picture.FileName);
                        string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Server.MapPath("~/Pictures/") + fileName;
                        data.Picture.SaveAs(savePath);
                        a.Picture = fileName;
                    }

                    a.Appointments.Clear();
                    this.repo.ExecuteCommand($"DELETE FROM Appointments WHERE PatientId={a.Id}");
                    this.repo.Update(a);

                    foreach (var item in data.Appointments)
                    {
                        this.repo.ExecuteCommand($"INSERT INTO Appointments([DoctorName], [AppointmentDate], PatientId) VALUES ('{item.DoctorName}', '{item.AppointmentDate}', {a.Id})");
                    }
                    return RedirectToAction("Index");
                }
            }

            ViewData["CurrentPic"] = db.Patients.First(x => x.Id == data.Id).Picture;
            return View(data);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            this.repo.ExecuteCommand($"dbo.DeletePatient {id}");
            return Json(new { success = true, deleted = id });
        }
    }
}

Hospital_Management_Systems/Hospital_Management_System/Views/Patients/Create.cshtml
@model Hospital_Management_System.ViewModels.PatientInputModel
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <div id="spnner" style="display:none">
            <div class="d-flex justify-content-end my-2">
                <div class="spinner-border text-warning" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>
        <div class="alert alert-success alert-dismissible fade show px-2" role="alert" id="successAlert" style="display:none">
            <strong>Success!</strong> Data saved successfully.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <div id="from-div">
            @using (Ajax.BeginForm("Create", "Patients", new { },
            new AjaxOptions
            {
                HttpMethod = "post",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "fields",
                LoadingElementId = "spnner",
                OnSuccess = "onSuccess"
            },
            new { enctype = "multipart/form-data", id = "frm" }))
            {
                <h3 class="mb-2 text-center"><b>Add new Patient</b></h3>
                <div id="fields">
                    @Html.Partial("_CreatePartial", Model)
                </div>
                <div class="form-group row mb-1">
                    <div class="d-flex justify-content-between">
                        <button type="button" class="btn btn-secondary" name="act" id="back" value="back">Back to Index</button>
                        <button type="submit" class="btn btn-primary" name="act" value="insert">Save to database</button>
                    </div>
                </div>
            }
        </div>
    </div>

</div>

@section styles
{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
}
@section scripts
{
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        $(() => {
            $(".ld").datepicker({
                format: "yyyy-mm-dd"
            });
            $(".ld").val('');
        });
        $(() => {
            $(".rd").datepicker({
                format: "yyyy-mm-dd"
            });
            $(".rd").val('');
        });

        function onSuccess() {
            if ($("#server-task").val() == "insert") {
                $('input[type=text]').val('');
                $('select').val('');
                $("#successAlert").show(); 2023 - 08 - 24
            }
        }
    </script>
    <script>
        $(() => {
             $("#back").click(function () {
                var indexURL = "@Url.Action("Index", "Patients")";
                window.location.href = indexURL;
            });
        });
    </script>
}

Hospital_Management_Systems/Hospital_Management_System/Views/Patients/Edit.cshtml
@model Hospital_Management_System.ViewModels.PatientEditModel
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-8">
        <div id="spnner" style="display:none">
            <div class="d-flex justify-content-end my-2">
                <div class="spinner-border text-warning" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>
        <div class="alert alert-warning alert-dismissible fade show px-2" role="alert" id="successAlert" style="display:none">
            <strong>Success!</strong> Data updated successfully.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        @using (Html.BeginForm("Edit", "Patients", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.Id)
            <h3 class="mb-2 text-center"><b>Edit Patient</b></h3>
            @Html.Partial("_EditPartial", Model)


            <div class="form-group row mb-1">
                <div class="d-flex justify-content-between">
                    <button type="button" class="btn btn-secondary" name="act" id="back" value="back">Back to Index</button>
                    <button type="submit" class="btn btn-primary" name="act" value="update">Save to database</button>
                </div>
            </div>

        }
    </div>

    <div class="col-4 ">
        <figure class="figure">
            <img src="~/Pictures/@ViewBag.CurrentPic" class="img-thumbnail" style="width: 150px; margin: 45px;" />
        </figure>

    </div>
</div>


@section styles
{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-icons-1.10.5/font/bootstrap-icons.css" rel="stylesheet" />
}
@section scripts {
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    

    <script>
        $(() => {
            $("#AdmissionDate").datepicker({
                format: "yyyy-mm-dd"
            })
            $("input[id$=AppointmentDate]").datepicker({
                format: "yyyy-mm-dd"
            })
             $("#back").click(function () {
                var indexURL = "@Url.Action("Index", "Patients")";
                window.location.href = indexURL;
             });
            $.each($("input[id$=AppointmentDate]"), (i, el) => {
                $(el).val(formatDate($(el).val()));
            })
            
        });
        function formatDate(dt) {
            console.log(dt);
            var d = new Date(dt);
            var date = [
                d.getFullYear(),
                ('0' + (d.getMonth() + 1)).slice(-2),
                ('0' + d.getDate()).slice(-2)
            ].join('-');
            return date;
        }
    </script>

}

Hospital_Management_Systems/Hospital_Management_System/Views/Patients/Index.cshtml
@model IEnumerable<Hospital_Management_System.Models.Patient>
@{
    ViewBag.Title = "Index";
}
@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common

@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-12">
        <h3 class="text-center"><b>Patient List</b></h3>

        <div class="d-flex justify-content-end mb-1">
            <a href="@Url.Action("Create", "Patients")" class="btn btn-primary btn-sm">Create New</a>
        </div>

        <table class="table table-bordered table-striped table-sm">
            <thead class="table-info text-center">
                <tr>
                    <th></th>
                    <th>Photo</th>
                    <th>Patient Name</th>
                    <th>Admission Date</th>
                    <th>Mobile</th>
                    <th>Gender</th>
                    <th>...</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var t in Model)
                {
                    <tr style="vertical-align:middle" id="tr_@t.Id">
                        <td class="text-center">
                            <button type="button" id="show_@t.Id" class="btn btn-outline-dark btn-sm show" data-aid="@t.Id"><i class="bi bi-chevron-right"></i></button>
                              <button type="button" id="hide_@t.Id" class="btn btn-outline-dark btn-sm  hide" data-aid="@t.Id" style="display:none"><i class="bi bi-chevron-down"></i></button>
                        </td>
                   
                        <td class="text-center"><img src="~/Pictures/@t.Picture" class="img-thumbnail rounded-1" style="width:50px" /></td>
                        <td>@t.PatientName</td>
                        <td>@t.AdmissionDate.ToString("yyyy-MM-dd")</td>
                        <td>@t.Mobile</td>
                        <td>@t.Gender</td>
                        <td class="text-center">
                            <a title="Edit this item" href="@Url.Action("Edit", "Patients", new {id=t.Id})" class="btn btn-success btn-sm"><i class="bi bi-pencil"></i> Edit</a>
                            <button type="button" title="Delete this item" data-pk="@t.Id" href="@Url.Action("Delete", "Patients", new {id=t.Id})" class="btn btn-danger btn-sm del"><i class="bi bi-trash"></i> Delete</button>
                        </td>
                    </tr>
                    <tr style="display:none" id="p_@t.Id">
                        <td></td>
                        <td colspan="8">
                            <h4 class="text-center">Appointment</h4>
                            <table class="table table-bordered table-sm">
                                <thead class="table-info ">
                                    <tr>
                                        <th>Doctor Name</th>
                                        <th>Appointment Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var p in t.Appointments)
                                    {
                                        <tr>
                                            <td>@p.DoctorName</td>
                                            <td>@p.AppointmentDate.ToString("yyyy-MM-dd")</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="d-flex justify-content-center">
            @Html.PagedListPager((IPagedList)Model, pg => Url.Action("Index", new { pg = pg }), new PagedListRenderOptions
            {
                LiElementClasses = new string[] { "page-item" },
                PageClasses = new string[] { "page-link" }
            })
        </div>
    </div>
</div>
<div class="modal" tabindex="-1" id="delmodal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-light">
                <h5 class="modal-title">Delete Patient</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure to delete?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="btnyes">Yes</button>
            </div>
        </div>
    </div>
</div>
@section styles
{
    <link href="~/Content/bootstrap-icons-1.10.5/font/bootstrap-icons.css" rel="stylesheet" />
}
@section scripts
{
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script>
        $(() => {
            $(".show").click(function () {
                var aid = $(this).data("aid");
                $(`#p_${aid}`).show();
                $(`#hide_${aid}`).show();
                $(this).hide();
            });
            $(".hide").click(function () {
                var aid = $(this).data("aid");
                $(`#p_${aid}`).hide();
                $(`#show_${aid}`).show();
                $(this).hide();
            })
        });
    </script>

    <script>
        var delModal;
        var delId = -1;
        $(() => {
            delModal = new bootstrap.Modal(document.getElementById('delmodal'));
            $(".del").click(function () {
                delModal.show();
                delId = $(this).data("pk");
                console.log(delId);
            });
            $("#btnyes").click(() => {
                $.ajax({
                    type: "post",
                    url: "/Patients/Delete/" + delId,
                    dataType: "json",
                    success: (r) => {
                        if (r.success == true) {
                            $("#tr_" + delId).remove();
                        }
                    }
                });
                delModal.hide();
            });
        })
    </script>
}

Hospital_Management_Systems/Hospital_Management_System/Views/Patients/_CreatePartial.cshtml
@model Hospital_Management_System.ViewModels.PatientInputModel

<input type="hidden" id="server-task" value="@ViewBag.Act" />

<div class="form-group row mb-1">
    @Html.LabelFor(x => x.PatientName, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.PatientName, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.PatientName, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.AdmissionDate, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.AdmissionDate, new { @class = "form-control form-control-sm est", type = "date" })
        @Html.ValidationMessageFor(x => x.AdmissionDate, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Mobile, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Mobile, new { @class = "form-select form-select-sm" })
        @Html.ValidationMessageFor(x => x.Mobile, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Gender, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.EnumDropDownListFor(x => x.Gender, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-6">
        @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
        @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="col-12">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Doctor Name</th>
                <th>Appointment Date</th>
                <th>
                    <button type="submit" class="btn btn-success btn-sm add" name="act" value="add" formnovalidate><i class="bi bi-plus"></i></button>
                </th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Appointments.Count; i++)
            {
                <tr>
                    <td>
                        @Html.TextBoxFor(x => Model.Appointments[i].DoctorName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => Model.Appointments[i].DoctorName, "", new { @class = "text-danger" })

                    </td>
                    <td>
                        @Html.TextBoxFor(x => Model.Appointments[i].AppointmentDate, new { @class = "form-control debut", type="date" })
                        @Html.ValidationMessageFor(x => Model.Appointments[i].AppointmentDate, "", new { @class = "text-danger" })
                    </td>

                    <th>
                        <button type="submit" class="btn btn-danger btn-sm" name="act" value="remove_@i" formnovalidate><i class="bi bi-trash"></i></button>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>

Hospital_Management_Systems/Hospital_Management_System/Views/Patients/_EditPartial.cshtml
@model Hospital_Management_System.ViewModels.PatientEditModel

<div class="form-group row mb-1">
    @Html.LabelFor(x => x.PatientName, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-10">
        @Html.TextBoxFor(x => x.PatientName, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.PatientName, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.AdmissionDate, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-10">
        @Html.TextBoxFor(x => x.AdmissionDate, new { @class = "form-control form-control-sm est" })
        @Html.ValidationMessageFor(x => x.AdmissionDate, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Mobile, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-10">
        @Html.TextBoxFor(x => x.Mobile, new { @class = "form-select form-select-sm" })
        @Html.ValidationMessageFor(x => x.Mobile, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Gender, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-10">
        @Html.EnumDropDownListFor(x => x.Gender, new { @class = "form-control form-control-sm" })
        @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="form-group row mb-1">
    @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-form-label-sm col-2" })
    <div class="col-10">
        @Html.TextBoxFor(x => x.Picture, new { @class = "form-control form-control-sm", type = "file" })
        @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger", style = "font-size:x-small" })
    </div>
</div>
<div class="col-12">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Doctor Name</th>
                <th>Appointment Date</th>
                <th>
                    <button type="submit" class="btn btn-success btn-sm add" name="act" value="add" formnovalidate><i class="bi bi-plus"></i></button>
                </th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Appointments.Count; i++)
            {
                <tr>
                    <td>
                        @Html.TextBoxFor(x => Model.Appointments[i].DoctorName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => Model.Appointments[i].DoctorName, "", new { @class = "text-danger" })

                    </td>
                    <td>
                        @Html.TextBoxFor(x => Model.Appointments[i].AppointmentDate, new { @class = "form-control debut" })
                        @Html.ValidationMessageFor(x => Model.Appointments[i].AppointmentDate, "", new { @class = "text-danger" })
                    </td>
                    <th>
                        <button type="submit" class="btn btn-danger btn-sm" name="act" value="remove_@i" formnovalidate><i class="bi bi-trash"></i></button>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>